#!/bin/sh -e

action="$1"
oldversion="$2"

if [ "$action" != configure ]; then
    exit 0
fi


if [ -x /etc/init.d/posa ]; then

    update-rc.d posa start 95 2 3 4 5 . stop 5 0 1 6 >/dev/null
    
    /etc/init.d/posa restart

fi


exit 0
