#!/bin/sh -e

action="$1"
oldversion="$2"

if [ "$action" != configure ]; then
    exit 0
fi


if [ -x /etc/init.d/posa ]; then
    if dpkg --compare-versions "$oldversion" lt "0.0.1"; then
        update-rc.d -f posa remove
    fi

    update-rc.d posa start 95 2 3 4 5 . >/dev/null
    if [ -x /usr/sbin/invoke-rc.d ]; then
        invoke-rc.d posa restart
    else
        /etc/init.d/posa restart
    fi
fi


exit 0
