bofcDb:
  # the name of your JDBC driver
  driverClass: org.h2.Driver

  # the username
  user: sa

  # the password
  password: 

  # the JDBC URL
  url: jdbc:h2:tcp://localhost:9092//var/lib/posa/backoffice;IFEXISTS=TRUE
  
  
posDb:
  # the name of your JDBC driver
  driverClass: net.sourceforge.jtds.jdbc.Driver

  # the username
# user: sa
# password: master

  user: fibu
  password: kasse2fibu
  
  # the JDBC URL
  #####  lokale datenbank
#  url: jdbc:jtds:sqlserver://localhost:1433/librasbak
  ##### im gschaeft Sulz
#  url: jdbc:jtds:sqlserver://localhost:7891/libras
  ##### im gschaeft Dornhan
  url: jdbc:jtds:sqlserver://localhost:7890/libras


articleGroupMappings:
  lotto:  { match : 'A00008TD', text : 'Lotto',  key : 'lotto', type : 'GOOD', marge : 0.05, account : '3631' }
  rubbellose: { match : 'A000082V', text : 'Rubbel-Lose',key : 'rubbellose', type: 'GOOD', marge : 0.02, account : '3632' }
  tickets: { match : 'A00008JI|[Rr]eservix|KKF.*',key : 'tickets', text : 'Reservix-Karten', type: 'GOOD', marge : 0.09, account : '1372' }  
  gutschJacob: { match : 'A000083V', text : 'Gutscheine Jacob',key : 'gutschJacob', type : 'COUPON', account : '1373' }
  gutschAllg: { match : 'A00008OO|Gutschein ', text : 'Gutschein Allg',key : 'gutschSchul', type : 'COUPON', account : '1373' }
  gutschDorn: { match : 'A00008BX', text : 'Gutschein Dornhan',key : 'gutschDorn', type : 'COUPON', account : '1371' }
  gutschSulz: { match : 'A00020TT', text : 'Gutschein Sulz',key : 'gutschSulz', type : 'COUPON', account : '1373' }
  zeitschrift: { match : 'A000082U', text : 'Zeitschriften',key : 'zeitschrift', type : 'GOOD', marge : 0.19 }
  gutsch: { match : '^Gutschein$', text : 'Gutschein',key : 'gutsch', type : 'COUPON', account : '1371' }
  schokolade: { match : 'A00008D0|A00008CZ', text : 'Schokolade',key : 'schokolade', type : 'GOOD', marge : 0.40 }
  karten: { match : '/k.*', text : 'Karten',key : 'karten', type : 'GOOD', marge : 0.5 }
  editio: { match : '/a.*', text : 'Edition',key : 'editio', type : 'GOOD', marge : 0.5 }
  book: { match : 'mwst=2', text : 'Bücher',key : 'book', type : 'GOOD', marge : 0.3 }
  nonbook: { match : 'mwst=1', text : 'NonBook',key : 'nonbook', type : 'GOOD', marge : 0.5 }
 
name: Test-Kasse  

idNumRangeStart: 7000

syncStartDate: 2014-10-01

pointOfSaleId: 6

homeUrl: http://192.168.2.111:8080/cashbalance/acceptBalance
#homeUrl: http://localhost:34343/cashbalance/acceptBalance
#homeHost: buchlese.selfhost.eu
homeHost: 192.168.2.111

sshEnabled: false


