bofcDb:
  # the name of your JDBC driver
  driverClass: org.h2.Driver

  # the username
  user: sa

  # the password
  password: 

  # the JDBC URL
#  url: jdbc:h2:tcp://localhost:19092///var/lib/posa/backoffice;IFEXISTS=TRUE
  url: jdbc:h2:~/backposa
  
  
posDb:
  # the name of your JDBC driver
  driverClass: net.sourceforge.jtds.jdbc.Driver

  # the username 
  user: sa
  password: master

#  user: fibu
#  password: kasse2fibu
  
  # the JDBC URL
  #####  lokale datenbank
#  url: jdbc:jtds:sqlserver://localhost:1433/librasbak
  ##### im gschaeft Sulz, Schramberg
  url: jdbc:jtds:sqlserver://localhost:7891/libras
  ##### im gschaeft Dornhan
#  url: jdbc:jtds:sqlserver://localhost:7890/libras


articleGroupMappings:
  lotto:  { wargrindex: 'L', match : 'A00008TD', text : 'Lotto',  key : 'lotto', type : 'GOOD', marge : 0.05, account : '3631' }
  rubbellose: { wargrindex: 'U', match : 'A000082V', text : 'Rubbel-Lose',key : 'rubbellose', type: 'GOOD', marge : 0.02, account : '3632' }
  tickets: { wargrindex: 'R', match : 'A00008JI|[Rr]eservix|KKF.*',key : 'tickets', text : 'Reservix-Karten', type: 'GOOD', marge : 0.09, account : '1372' }  
  zeitschrift: { wargrindex: 'Z', match : 'A000082U', text : 'Zeitschriften',key : 'zeitschrift', type : 'GOOD', marge : 0.19 }
  gutsch: { wargrindex: 'G', match : '^Gutschein$', text : 'Gutschein',key : 'gutsch', type : 'COUPON', account : '1371' }
  schokolade: { wargrindex: 'O', match : 'A00008D0|A00008CZ', text : 'Schokolade',key : 'schokolade', type : 'GOOD', marge : 0.40 }
  karten: { wargrindex: 'K', match : '/k.*', text : 'Postkarten',key : 'karten', type : 'GOOD', marge : 0.5 }
  editio: { wargrindex: '9', match : '/a.*', text : 'Editio Käpsele',key : 'editio', type : 'GOOD', marge : 0.5 }
  book: { wargrindex: '0123', match : 'mwst=2', text : 'Bücher',key : 'book', type : 'GOOD', marge : 0.3 }
  tee: { wargrindex: 'T', match : 'mwst=1', text : 'Tee',key : 'tee', type : 'GOOD', marge : 0.5 }
  schreibwaren: { wargrindex: 'S', match : 'mwst=1', text : 'Schreibwaren',key : 'schreibw', type : 'GOOD', marge : 0.5 }
  kalender: { wargrindex: '7', match : 'mwst=1', text : 'Kalender',key : 'kalender', type : 'GOOD', marge : 0.3 }
  nonbook: { wargrindex: '4568', match : 'mwst=1', text : 'NonBook',key : 'nonbook', type : 'GOOD', marge : 0.5 }
 
name: Test-Kasse  

pointOfSaleId: 6

syncOffset: 2
sendOffset: 1
syncInterval: 2
sendInterval: 2
commandOffset: 1
commandInterval: 1

#homeUrl: http://localhost:7896/
homeUrl: http://localhost:8082/
#homeHost: buchlese.selfhost.eu
homeHost: 127.0.0.1

cashBalanceResource: balances/acceptBalance
invoiceResource: invoices/acceptInvoice
issueSlipResource: issueslips/acceptIssueSlip
posStateResource: state/acceptPosState
serverStateResource: state/acceptServerState
commandGetResource: commands/getCmds
commandSendResource: commands/acceptCmdAnswer

sshEnabled: false

server:
  applicationConnectors:
  - type: http 
    port: 9000
  adminConnectors:
  - type: http
    port: 9001



