bofcDb:
  driverClass: org.h2.Driver
  user: sa
  password:
  
  # the JDBC URL 
  # vom cubietruck
#  url: jdbc:h2:tcp://192.168.2.111:9092//var/lib/bofc/backoffice;IFEXISTS=TRUE
  url: jdbc:h2:~/backofficeg
#  url: jdbc:h2:tcp://localhost:19092//var/lib/bofc/backoffice;IFEXISTS=TRUE


jpamysql:
  driverClass: com.mysql.jdbc.Driver
  user: bofc
  password: bofc
  url: jdbc:mysql://localhost:3306/bofc
  properties:
    charSet: UTF-8
    useSSL: false
    hibernate.dialect: org.hibernate.dialect.MySQLDialect
    hibernate.hbm2ddl.auto: create

  
articleGroupMappings:
  lotto:  { wargrindex: 'L', text : 'Lotto',  key : 'lotto', type : 'GOOD', marge : 0.05, account : '1373' }
  rubbellose: { wargrindex: 'U', text : 'Rubbel-Lose',key : 'rubbellose', type: 'GOOD', marge : 0.02, account : '1373' }
  tickets: { wargrindex: 'R', key : 'tickets', text : 'Reservix-Karten', type: 'GOOD', marge : 0.09, account : '1372' }  
  zeitschrift: { wargrindex: 'Z', text : 'Zeitschriften',key : 'zeitschrift', type : 'GOOD', marge : 0.19 }
  gutsch: { wargrindex: 'G', text : 'Gutschein',key : 'gutsch', type : 'COUPON', account : '1371' }
  schokolade: { wargrindex: 'O', text : 'Schokolade',key : 'schokolade', type : 'GOOD', marge : 0.40 }
  karten: { wargrindex: 'K', text : 'Postkarten',key : 'karten', type : 'GOOD', marge : 0.5 }
  editio: { wargrindex: '9', text : 'Editio Käpsele',key : 'editio', type : 'GOOD', marge : 0.5 }
  book: { wargrindex: '0123', text : 'Bücher',key : 'book', type : 'GOOD', marge : 0.3 }
  tee: { wargrindex: 'T', text : 'Tee',key : 'tee', type : 'GOOD', marge : 0.5 }
  schreibwaren: { wargrindex: 'S', text : 'Schreibwaren',key : 'schreibw', type : 'GOOD', marge : 0.5 }
  kalender: { wargrindex: '7', text : 'Kalender',key : 'kalender', type : 'GOOD', marge : 0.3 }
  nonbook: { wargrindex: '4568', text : 'NonBook',key : 'nonbook', type : 'GOOD', marge : 0.5 }

